[build-system]
requires = ["scikit-build-core>=0.11.6"]
build-backend = "scikit_build_core.build"

[project]
name = "umodl"
version = "0.0.29"
description = "A 'subprocess.run' wrapper around the umodl program"
readme = "README.md"
requires-python = ">=3.9"
license = "BSD-3-Clause-Clear"
license-files = ["LICENSE"]
maintainers = [{name="The Khiops Team", email="khiops.team@orange.com"}]

[project.urls]
source = "https://github.com/UData-Orange/umodl.git"

[tool.scikit-build]
wheel.py-api = "py3"
wheel.packages = ["packaging/python/umodl"]
cmake.version = "CMakeLists.txt"
build.targets = ["umodl"]
install.components = ["umodl"]  # Only install umodl, not KNI or anything else.
ninja.make-fallback = false

[[tool.scikit-build.overrides]]
if.platform-system = "^linux"
cmake.args = ["--preset", "linux-gcc-release", "-G", "Ninja"]
build-dir = "build/linux-gcc-release"
cmake.define.CMAKE_BINARY_DIR = "build/linux-gcc-release"
cmake.define.PACKAGING_FOR_PYTHON = true
cmake.define.MPI = false
cmake.define.TESTING=false

[[tool.scikit-build.overrides]]
if.platform-system = "^darwin"
cmake.args = ["--preset", "macos-clang-release", "-G", "Ninja"]
build-dir = "build/macos-clang-release"
cmake.define.CMAKE_BINARY_DIR = "build/macos-clang-release"
cmake.define.PACKAGING_FOR_PYTHON = true
cmake.define.MPI = false
cmake.define.TESTING=false

[[tool.scikit-build.overrides]]
if.platform-system = "^win32"
cmake.args = ["--preset", "windows-msvc-release", "-G", "Ninja"]
build-dir = "build/windows-msvc-release"
cmake.define.CMAKE_BINARY_DIR = "build/windows-msvc-release"
cmake.define.PACKAGING_FOR_PYTHON = true
cmake.define.MPI = false
cmake.define.TESTING=false

[tool.cibuildwheel]
build = "cp39-*"
skip = "*musllinux*"  # umodl does not support musllinux
archs = "auto64"  # Do not build 32-bit wheels

# Install build-time dependencies in containers created by cibuildwheel
# This is compatible with Debian-like and Fedora-like distributions
[tool.cibuildwheel.linux]
before-all = [
    "DEB_NEEDS='zip perl ninja-build'",
    "FED_NEEDS='zip perl ninja-build'",
    "apt-get install -y $DEB_NEEDS || dnf install -y $FED_NEEDS"
]